version: '3'
volumes:
  postgres_data: {}
  elastic_data: {}
  nginx_cache: {}
  booru_data: {}

services:
  init:
    image: busybox
    volumes:
      - booru_data:/srv/assets/static/system
    command: /bin/chown -v 200:200 /srv/assets/static/system
    restart: "no"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile.app
    environment:
      - MIX_ENV=dev
      - PGPASSWORD=postgres
      - PGDATABASE=philomena_db
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - SECRET_KEY_BASE=pofhuztofzewtrzrkzswtq9f3vqeslsobklifmdsekklsjetrdrdk.ykskueif,zorvuz97rersn
      - PASSWORD_PEPPER=jiegjdfoigjerjgijviojewjniojotuizufddyxrekökhoijuogduekj
    tty: true
    depends_on:
      - postgres
      - elasticsearch
      - redis
    volumes:
      - booru_data:/srv/assets/static/system
    # for debugging into the container when container-start fails, umcomment the following line:
    #entrypoint: ["sh", "-c", "sleep 2073600"]

  gdpr-cron:
    build:
      context: ./docker/gdpr
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
      PGDATABASE: philomena_db
      PGUSER: postgres
      PGPASSWORD: postgres

  postgres:
    image: postgres:12.3
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: "none"

  elasticsearch:
    image: elasticsearch:7.6.2
    volumes:
      - elastic_data:/var/lib/elasticsearch
    logging:
      driver: "none"
    environment:
      - discovery.type=single-node
    ulimits:
      nofile:
          soft: 65536
          hard: 65536

  redis:
    image: redis:5.0.9
    logging:
      driver: "none"

  web:
    build:
      context: .
      dockerfile: ./Dockerfile.web
    depends_on:
      - app
    extra_hosts:
      - kube-dns.kube-system.svc.cluster.local:127.0.0.11
    environment:
      - APP_HOST=app
    tmpfs:
      - /tmp
    ports:
      - '8080:8080'
    volumes:
      - booru_data:/system
      - booru_data:/srv/philomena/priv/static/system
